"""
TASI Financial Database - SQL Validation Module
Validates and sanitizes LLM-generated SQL queries for safe execution.
"""

import re
from dataclasses import dataclass
from typing import List, Tuple, Optional, Set
from enum import Enum

from logger import get_logger

logger = get_logger("sql_validator")


class ValidationSeverity(Enum):
    """Severity levels for validation issues."""
    ERROR = "error"      # Query cannot be executed
    WARNING = "warning"  # Query can run but has concerns
    INFO = "info"        # Informational note


@dataclass
class ValidationResult:
    """Result of SQL validation."""
    is_valid: bool
    sql: str
    issues: List[Tuple[ValidationSeverity, str]]
    modified: bool = False  # Whether SQL was modified during validation

    @property
    def errors(self) -> List[str]:
        return [msg for sev, msg in self.issues if sev == ValidationSeverity.ERROR]

    @property
    def warnings(self) -> List[str]:
        return [msg for sev, msg in self.issues if sev == ValidationSeverity.WARNING]


class SQLValidator:
    """
    Validates SQL queries generated by LLM for safe execution.

    Security features:
    - Blocks dangerous DDL/DML operations (DROP, DELETE, INSERT, etc.)
    - Validates table references against allowed list
    - Enforces row limits on queries without LIMIT
    - Detects SQL injection patterns
    - Blocks system table access
    """

    # Dangerous SQL keywords that modify data/schema
    BLOCKED_KEYWORDS = {
        # DDL operations
        "DROP", "CREATE", "ALTER", "TRUNCATE",
        # DML operations (except SELECT)
        "INSERT", "UPDATE", "DELETE", "MERGE", "UPSERT",
        # Permission operations
        "GRANT", "REVOKE",
        # Execution operations
        "EXEC", "EXECUTE", "CALL",
        # Copy operations
        "COPY",
        # Comment modification
        "COMMENT ON",
    }

    # System tables/schemas that should never be queried
    BLOCKED_SCHEMAS = {
        "pg_catalog",
        "information_schema",
        "pg_toast",
    }

    # Patterns that suggest SQL injection attempts
    INJECTION_PATTERNS = [
        r";\s*DROP",           # Statement chaining with DROP
        r";\s*DELETE",         # Statement chaining with DELETE
        r";\s*INSERT",         # Statement chaining with INSERT
        r";\s*UPDATE",         # Statement chaining with UPDATE
        r"--\s*$",             # Comment at end of line
        r"/\*.*\*/",           # Block comments
        r"UNION\s+SELECT",     # Union injection
        r"INTO\s+OUTFILE",     # File writing
        r"INTO\s+DUMPFILE",    # File writing
        r"LOAD_FILE",          # File reading
    ]

    # Default allowed tables
    DEFAULT_ALLOWED_TABLES = {
        "company_financials",
        "companies",
        "sectors",
        "fiscal_periods",
        "financial_statements",
        "financial_metrics",
    }

    def __init__(
        self,
        allowed_tables: Optional[Set[str]] = None,
        max_rows: int = 1000,
        enable_strict_mode: bool = True
    ):
        """
        Initialize SQL validator.

        Args:
            allowed_tables: Set of table names that can be queried
            max_rows: Maximum rows to return (added as LIMIT if missing)
            enable_strict_mode: If True, unknown tables cause errors; if False, warnings
        """
        self.allowed_tables = allowed_tables or self.DEFAULT_ALLOWED_TABLES
        self.max_rows = max_rows
        self.enable_strict_mode = enable_strict_mode

    def validate(self, sql: str) -> ValidationResult:
        """
        Validate an SQL query.

        Args:
            sql: The SQL query to validate

        Returns:
            ValidationResult with validation status and any issues found
        """
        issues: List[Tuple[ValidationSeverity, str]] = []
        modified_sql = sql.strip()
        was_modified = False

        # Remove markdown code blocks if present
        modified_sql, code_block_removed = self._clean_markdown(modified_sql)
        if code_block_removed:
            was_modified = True

        # Check for empty SQL
        if not modified_sql:
            issues.append((ValidationSeverity.ERROR, "Empty SQL query"))
            return ValidationResult(False, sql, issues)

        # Normalize SQL for checking (uppercase for keyword matching)
        sql_upper = modified_sql.upper()

        # Check for blocked keywords
        blocked = self._check_blocked_keywords(sql_upper)
        if blocked:
            issues.append((
                ValidationSeverity.ERROR,
                f"Blocked SQL operation(s) detected: {', '.join(blocked)}"
            ))
            logger.warning(f"Blocked SQL keywords detected: {blocked}", sql=sql[:200])

        # Check for injection patterns
        injections = self._check_injection_patterns(modified_sql)
        if injections:
            issues.append((
                ValidationSeverity.ERROR,
                f"Potential SQL injection pattern detected: {', '.join(injections)}"
            ))
            logger.warning(f"SQL injection pattern detected", sql=sql[:200])

        # Check for system table access
        system_access = self._check_system_tables(sql_upper)
        if system_access:
            issues.append((
                ValidationSeverity.ERROR,
                f"Access to system tables blocked: {', '.join(system_access)}"
            ))

        # Validate table references
        table_issues = self._check_table_references(modified_sql)
        issues.extend(table_issues)

        # Check if SELECT query
        if not self._is_select_query(sql_upper):
            issues.append((
                ValidationSeverity.ERROR,
                "Only SELECT queries are allowed"
            ))

        # Add LIMIT if missing
        if self._is_select_query(sql_upper) and not self._has_limit(sql_upper):
            modified_sql = self._add_limit(modified_sql)
            was_modified = True
            issues.append((
                ValidationSeverity.INFO,
                f"Added LIMIT {self.max_rows} to query"
            ))

        # Check for multiple statements
        if self._has_multiple_statements(modified_sql):
            issues.append((
                ValidationSeverity.ERROR,
                "Multiple SQL statements are not allowed"
            ))

        # Determine if valid
        has_errors = any(sev == ValidationSeverity.ERROR for sev, _ in issues)

        return ValidationResult(
            is_valid=not has_errors,
            sql=modified_sql,
            issues=issues,
            modified=was_modified
        )

    def _clean_markdown(self, sql: str) -> Tuple[str, bool]:
        """Remove markdown code blocks from SQL."""
        original = sql
        # Remove ```sql or ``` blocks
        if sql.startswith("```sql"):
            sql = sql[6:]
        elif sql.startswith("```"):
            sql = sql[3:]
        if sql.endswith("```"):
            sql = sql[:-3]
        return sql.strip(), sql.strip() != original

    def _check_blocked_keywords(self, sql_upper: str) -> List[str]:
        """Check for blocked SQL keywords."""
        found = []
        for keyword in self.BLOCKED_KEYWORDS:
            # Use word boundary matching to avoid false positives
            pattern = rf"\b{keyword}\b"
            if re.search(pattern, sql_upper):
                found.append(keyword)
        return found

    def _check_injection_patterns(self, sql: str) -> List[str]:
        """Check for SQL injection patterns."""
        found = []
        for pattern in self.INJECTION_PATTERNS:
            if re.search(pattern, sql, re.IGNORECASE):
                found.append(pattern)
        return found

    def _check_system_tables(self, sql_upper: str) -> List[str]:
        """Check for system table/schema access."""
        found = []
        for schema in self.BLOCKED_SCHEMAS:
            if schema.upper() in sql_upper:
                found.append(schema)
        return found

    def _check_table_references(self, sql: str) -> List[Tuple[ValidationSeverity, str]]:
        """Check table references against allowed list."""
        issues = []

        # Extract table names from FROM and JOIN clauses
        # This is a simplified pattern and may not catch all cases
        from_pattern = r"\bFROM\s+([a-zA-Z_][a-zA-Z0-9_]*)"
        join_pattern = r"\bJOIN\s+([a-zA-Z_][a-zA-Z0-9_]*)"

        tables = set()
        for pattern in [from_pattern, join_pattern]:
            matches = re.findall(pattern, sql, re.IGNORECASE)
            tables.update(t.lower() for t in matches)

        # Check each table
        for table in tables:
            if table not in {t.lower() for t in self.allowed_tables}:
                severity = ValidationSeverity.ERROR if self.enable_strict_mode else ValidationSeverity.WARNING
                issues.append((
                    severity,
                    f"Table '{table}' is not in the allowed list"
                ))

        return issues

    def _is_select_query(self, sql_upper: str) -> bool:
        """Check if query is a SELECT statement."""
        # Strip leading whitespace and WITH clauses
        sql_clean = sql_upper.strip()
        return sql_clean.startswith("SELECT") or sql_clean.startswith("WITH")

    def _has_limit(self, sql_upper: str) -> bool:
        """Check if query has a LIMIT clause."""
        return bool(re.search(r"\bLIMIT\s+\d+", sql_upper))

    def _add_limit(self, sql: str) -> str:
        """Add LIMIT clause to query."""
        # Remove trailing semicolon if present
        sql = sql.rstrip().rstrip(";")
        return f"{sql} LIMIT {self.max_rows}"

    def _has_multiple_statements(self, sql: str) -> bool:
        """Check for multiple SQL statements."""
        # Look for semicolons that aren't in strings
        # This is a simplified check
        in_string = False
        string_char = None

        for i, char in enumerate(sql):
            if char in ("'", '"') and (i == 0 or sql[i-1] != "\\"):
                if not in_string:
                    in_string = True
                    string_char = char
                elif char == string_char:
                    in_string = False
                    string_char = None
            elif char == ";" and not in_string:
                # Check if there's more content after the semicolon
                remaining = sql[i+1:].strip()
                if remaining and not remaining.startswith("--"):
                    return True

        return False


def validate_sql(sql: str, max_rows: int = 1000) -> ValidationResult:
    """
    Convenience function to validate SQL.

    Args:
        sql: SQL query to validate
        max_rows: Maximum rows to allow

    Returns:
        ValidationResult
    """
    validator = SQLValidator(max_rows=max_rows)
    return validator.validate(sql)


def is_safe_sql(sql: str) -> bool:
    """
    Quick check if SQL is safe to execute.

    Args:
        sql: SQL query to check

    Returns:
        True if safe, False otherwise
    """
    result = validate_sql(sql)
    return result.is_valid
